### ISSUE TITLE
Breaks project and SDK

### ISSUE THREAD

**Issue by NotKenny2448** [VRLabs/Avatars-3.0-Manager#10]
Keep trying to merge FX layers with tool. When ever I import. No tool appears and I get errors in my console. Breaks SDK. Only way to fix is removing from project. Tried multiple versions and still does not work.

**Comment by Cibbi** [comment]
You probably have an old version of the SDK installed. Instal the new one before installing the manager. If it continues to error check the errors on the console.

We have a dedicated section on out [Discord server](https://discord.vrlabs.dev) with common issues people have with the manager.
