### ISSUE TITLE
Messed up left expression Gestures

### ISSUE THREAD

**Issue by SweetPeachyBread** [VRLabs/Avatars-3.0-Manager#11]
Ever since I've used the VrLabs that I was instructed to use from a youtube video on about hand contacts, my left hand gestures expression hasn't been working and it made a different expression as my idle expression. I've tried to reinvert it on how it was originally. The expression gesture did came back but the hands were no longer working.

**Comment by Cibbi** [comment]
For support in usage please go to the support chat of our [discord](https://discord.vrlabs.dev).
