### ISSUE TITLE
Older version that supports VRCSDK 22.07.26.21.45/Unity 2019?

### ISSUE THREAD

**Issue by red1134** [VRLabs/Avatars-3.0-Manager#38]
I know already that the latest version is also meant for the latest SDK. However, I have been using an outdated SDK for a long time out of laziness (hate waiting for SDK to reimport). I am also still on Unity 2019 because my project is absolutely **massive,** like 90+gb massive and would take ages to reimport everything into unity so I'm not updating until it is absolutely 100% necessary. Is there any older versions of this that would work with the stated SDK and Unity versions? If so, could you point me to the exact version that would support this?

**Comment by Cibbi** [comment]
In https://github.com/VRLabs/Avatars-3.0-Manager/releases you have all the releases we ever released of the manager.

Now saying "an old sdk version of 2019" is not specific enough to pinpoint a version of the manager that would work on your version of the sdk. 

In fact there have been quite a few breaking changes with sdk versions in unity 2019 with consequent updates on the manager to fix the related issues.

For sdk versions from 3.2.0 up to the latest (3.5 family of versions for unity 2022) the latest version of the manager still works with it.

for older versions of the sdk, you will need to looks for versions of the manager older than 2.0.23.

If you provide exactly which version of the sdk you have, i can point you towards a version of the manager that works with it

**Comment by Cibbi** [comment]
I would give a try with the latest version first (it still supports old sdks, although i don't know i it support that one specifically)

If it doesn't work, try [2.0.23](https://github.com/VRLabs/Avatars-3.0-Manager/releases/tag/2.0.23), if it still too new of a version proceed backwards

[2.0.12](https://github.com/VRLabs/Avatars-3.0-Manager/releases/tag/2.0.12) was released about the same time the version you mentioned in the title released, that would be the best bet compatibility wise, but that version is so old it probably has a lot of bugs we found out later
