### ISSUE TITLE
Copied parameters keep getting deleted

### ISSUE THREAD

**Issue by ShayBox** [VRLabs/Avatars-3.0-Manager#4]
After restarting unity, or the next day any copied parameter with this tool get wiped

**Comment by oofdesu** [comment]
The parameters in the merged controller, or the ones in the parameter asset? Can you give an example or controller we can inspect?

**Comment by ShayBox** [comment]
In the merged controller, I duplicate a gogo parameter controller and merge my avatars parameters into it, upload, and later when I come back my avatars parameters are missing from the duplicated gogo controller.
I can reproduce it using any of my avatars, just restarting unity, maybe it has to do with using a duplicated gogo controller (Ctrl-D)

**Comment by oofdesu** [comment]
I cannot reproduce this yet. I have tried merging a controller, and exiting Unity without saving, but when Unity re-opens my controller is still fine. However, I do notice that my changes to the avatar descriptor do not save, and it's still referencing an older controller. Could it be that your controllers are similarly named, and your descriptor is reverting to the controller that hasn't had anything merged to it?

**Comment by ShayBox** [comment]
I add `+ Custom Parameters` to the end of my duplicated parameters file name, so `Go Beyond Parameters + Custom Parameters`.  
Go Beyond Parameters is a file in a different folder I duplicated.  
Custom Parameters is a file in the same folder as my duplicated file that I'm copying/merging.

**Comment by ShayBox** [comment]
Here's a video of it https://youtu.be/qGG_10hyDxU

**Comment by Cibbi** [comment]
Thank you for the report.

The issue has been fixed on version 2.0.11

Keep in mind that the parameters asset still wont be saved if unity closes abnormaly, but that would be expected behaviour. 
But now if you close it normally (or just save) it will save like it should.

I'll wait for confirmation on your end before closing this issue.

**Comment by ShayBox** [comment]
That fixed it, thank you 👍
