### ISSUE TITLE
Merging causes duplicates with same names with zero at the end

### ISSUE THREAD

**Issue by chrispyni** [VRLabs/Avatars-3.0-Manager#40]
When I merge layers it causes dublicates with 0 at the end.
For example, gesture layer have "AllParts 0", "Left Hand 0", "Right Hand 0"

**Comment by jellejurre** [comment]
This is intended, if you merging copies over all layers of the target controller, even if they already exist. If you want to only merge certain layers you need a controller with just those layers.
