### ISSUE TITLE
Custom int (and possibly float) parameter sizes

### ISSUE THREAD

**Issue by EnderShadow** [VRLabs/Avatars-3.0-Manager#41]
It's pretty common to use an `int` or `float` parameter as a way to select mutually exclusive things. It's also pretty common to only use a few of the bits in the parameter and thus waste some of them. Normally this is fine, but with complex avatars this can be limiting since only 256 bits of synced parameter is available.

It would be nice to have a way to create custom sized parameters that get mapped to multiple `bool` parameters in order to reduce the number of used synced bits. Here's an idea of how it might work.

1. A local parameter (of type `int` or `float`) is defined in the avatar's parameters.
2. An animator parameter of a similar (or the same) name is defined.
3. A parameter is defined in the avatar manager with type `int` or `float` as well as a number of bits.
4. The local parameter is split into a number of `bool` parameters by defining synced parameters on the avatar and somehow assigned so that changes to the local parameter changes these `bool` parameters.
5. The bool parameters are used to re-create an `int` or `float` which is used in the animation controller.

Examples:

You define an `int` parameter with 2 bits named `foo`. This would turn into `foo0` and `foo1` which would be used to assign an animation parameter named `foo` to either 0, 1, 2, or 3.

You define a `float` parameter with 2 bits named `bar`. This would turn into `bar0` and `bar1` which would be used to assign an animation parameter named `bar` to either 0.0, 0.333, 0.666, or 1.0.

**Comment by jellejurre** [comment]
While this is useful functionality, it is out of scope for the Avatars 3.0 Manager.

I recommend looking at https://github.com/JeTeeS/MemoryOptimizer
