### ISSUE TITLE
Resolve or block parameter type conflicts

### ISSUE THREAD

**Issue by azukitiger** [VRLabs/Avatars-3.0-Manager#50]
It's unusual for the main avatar FX controller to use Floats for the GestureLeft, GestureRight and IsLocal parameters but I do for my own to implement improved smoothing (non linear) by using blendtrees, many assets that use these parameters will break when merging their FX controller as the transition conditions aren't the right type (not an Integer or Boolean).

Can you make it so mismatched types don't allow merging the FX controller or resolving the conflicts by replacing the conditions to valid ones based on the parameter type.

I would at least like the block to implemented so that asset creators don't get asked why their asset isn't working.

**Comment by jellejurre** [comment]
Fixed on latest version, on detection of a mismatched parameter type it'll mention that these two controllers are not compatible and disallow merges
