### ISSUE TITLE
Vrlab not showing up in unity

### ISSUE THREAD

**Issue by Turtlecatplayz** [VRLabs/Avatars-3.0-Manager#6]
I have the latest version on the VrChat SDK and Avatars-3.0-Manager.
When i imported the package, the VrLab button at the top of unity does not show up, I have redownloaded it to see if that was the issue and it wasn't.

**Comment by Cibbi** [comment]
That is usually indication on a compilation error in your unity project, check the console

For general support you should come and ask on our [discord](https://discord.vrlabs.dev), we answer this kind of questions fairly quickthere, github issues is usually a place for more technical people to report bugs and technical problems.

**Comment by HyperBeast43** [comment]
i checked the console and all it says is a bunch of `'VRCExpressionParameters.Parameter' does not contain a definition for 'networkSynced'`
