### ISSUE TITLE
Support merging menus

### ISSUE THREAD

**Issue by imagitama** [VRLabs/Avatars-3.0-Manager#8]
I have different avatar variations that each need their own variation of a base menu. I would like this tool to be able to merge menus together (like controllers and params). eg:

Base Menu
Custom Menu - Variation A
Custom Menu - Variation B

You would be able to merge every item from Custom Menu - Variation A into the Base Menu. For your other avatar you would merge Variation B. etc.

This is my current list of menus as an example:

![image](https://user-images.githubusercontent.com/1967342/191664084-679ca850-57f8-4917-95c5-877c019bb7fa.png)

**Comment by Cibbi** [comment]
I'm gonna pull a "soonTM" on that one.

I have a couple of ideas for menu management, but there are some things that need to be done before that.

**Comment by Ashlien** [comment]
I need help i keep getting this error and don't know how to fix it. There are a few others related
 Assets\VRLabs\Avatars 3.0 Manager\Editor\AnimatorCloner.cs(333,49): error CS1061: 'VRC_AvatarParameterDriver.Parameter' does not contain a definition for 'sourceParam' and no accessible extension method 'sourceParam' accepting a first argument of type 'VRC_AvatarParameterDriver.Parameter' could be found (are you missing a using directive or an assembly reference?)

**Comment by Cibbi** [comment]
This is not the place for support requests, check on our discord for that, also it is unrelated to the issue posted by @imagitama 

Closing this issue until i get back to the menu management
